version: "3.8"

services:
  postgres:
    image: postgres:13.0
    container_name: postgresql
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=postgres
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    ports:
      - "9000:5432"
    restart: always

volumes:
  postgres_volume:
    driver: local
